Repository Kit/convertkit-wordpress, pull requests merged in 2019-01, with the labels that each got.

#136 Issue/124
  .gitignore
  admin/class-convertkit-settings.php
  admin/section/class-convertkit-settings-general.php
  includes/class-convertkit-api.php
  resources/backend/wp-convertkit.js
Labels: enhancement

#142 Move old libraries out of /vendor to /lib
  includes/class-convertkit-api.php
  lib/README.md
  lib/simple-html-dom/simple-html-dom.php
  lib/url-to-absolute/url-to-absolute.php
Labels: ready for review

#153 Only call ConvertKit_Custom_Content::maybe_tag_subscriber() on actual pages/posts
  includes/class-convertkit-custom-content.php
Labels: bug, minor, ready for review

#155 Feature/release process
  .distignore
  bin/package.sh
Labels: enhancement, ready for review

#158 Don't remove ck_subscriber_id from URL until we set a cookie
  resources/frontend/wp-convertkit.js
Labels: bug, ready for review

#149 Make the custom content feature work properly
  resources/frontend/wp-convertkit.js
Labels: bug

#160 Force WishList Member integration settings to be saved as an array
  admin/section/class-convertkit-settings-wishlist.php
Labels: bug, ready for review

#123 Fix for when landing page id is not set.
  includes/class-convertkit.php
Labels: bug, ready for review

#150 Adding tools tab.
  admin/class-convertkit-settings.php
  admin/section/class-convertkit-settings-base.php
  admin/section/class-convertkit-settings-tools.php
  lib/browser.php
  resources/backend/wp-convertkit.css
  wp-convertkit.php
Labels: enhancement, ready for review

#161 Release/1.6.4
  .distignore
  .gitignore
  admin/class-convertkit-settings.php
  admin/section/class-convertkit-settings-base.php
  admin/section/class-convertkit-settings-tools.php
  admin/section/class-convertkit-settings-wishlist.php
  bin/package.sh
  includes/class-convertkit-api.php
  includes/class-convertkit-custom-content.php
  includes/class-convertkit.php
  lib/README.md
  lib/browser.php
  lib/simple-html-dom/simple-html-dom.php
  lib/url-to-absolute/url-to-absolute.php
  package.json
  readme.txt
  resources/backend/wp-convertkit.css
  resources/frontend/wp-convertkit.js
  wp-convertkit.php
Labels: ship

#163 Feature/testing
  codeception.dist.yml
  composer.json
  composer.lock
  tests/_data/.gitkeep
  tests/_data/dump.sql
  tests/_output/.gitignore
  tests/_support/AcceptanceTester.php
  tests/_support/FunctionalTester.php
  tests/_support/Helper/Acceptance.php
  tests/_support/Helper/Functional.php
  tests/_support/Helper/Unit.php
  tests/_support/Helper/Wpunit.php
  tests/_support/UnitTester.php
  tests/_support/WpunitTester.php
  tests/_support/_generated/.gitignore
  tests/acceptance.suite.yml
  tests/acceptance/SignInCest.php
  tests/bootstrap.php
  tests/functional.suite.yml
  tests/functional/PostInsertionCept.php
  tests/test-filters.php
  tests/test-sample.php
  tests/unit.suite.yml
  tests/wpunit.suite.yml
  tests/wpunit/Acme/SomeClassTest.php
Labels: enhancement

#162 Improve performance of our javascript for fun and profit
  admin/section/class-convertkit-settings-general.php
  includes/class-convertkit.php
  resources/frontend/wp-convertkit.js
Labels: enhancement, ready for review

#169 Only strip out ck_subscriber_id from URL query parameters
  resources/frontend/wp-convertkit.js
Labels: bug, ready for review
